export const blogList = [
    {
      id: 1,
      title: '7 CSS tools you should be using ',
      category: 'design',
      subHeader: 'Maximize Your Productivity with These Must-Have CSS Utilities',
      subCategory: ['frontend', 'ui/ux', 'design'],
      description:
        "CSS, or Cascading Style Sheets, is a stylesheet language used for describing the look and formatting of a document written in HTML. It is a powerful tool for controlling the visual appearance of web pages and applications, and there are a number of CSS tools available that can make working with CSS faster and more efficient. Here are seven CSS tools that you should be using CSS Preprocessor: A CSS preprocessor is a tool that allows you to write CSS in a more powerful and efficient way. Preprocessors add features such as variables, mixins, and functions to CSS, which can help you avoid repeating code and make your stylesheets easier to maintain. Popular CSS preprocessors include Sass and Less.CSS Grid: CSS Grid is a powerful layout system that allows you to create complex and responsive layouts using only CSS. It is an essential tool for building modern, responsive websites and applications.CSS Framework: A CSS framework is a collection of CSS styles and layout patterns that can be used as a starting point for building websites and applications. Frameworks such as Bootstrap and Foundation provide a set of predefined styles and layout options that can save you time and effort when building your projects.CSS Normalizer: A CSS normalizer is a tool that helps you ensure that your stylesheets are consistent across different browsers. Normalizers can help you avoid the frustrating task of debugging CSS issues caused by differences in how different browsers interpret and apply styles.CSS Validator: A CSS validator is a tool that checks your CSS code for errors and ensures that it follows the syntax and formatting rules of the CSS language. Validators can help you catch mistakes and prevent issues from arising in your stylesheets.CSS Minifier: A CSS minifier is a tool that reduces the size of your CSS files by removing unnecessary characters and formatting. Minifiers can help you optimize your website's performance by reducing the size of your stylesheets and speeding up the loading time of your pages.CSS Autoprefixer: A CSS autoprefixer is a tool that adds vendor prefixes to your CSS code automatically. Vendor prefixes are required for certain CSS properties and values in order to ensure that they are supported by different browsers. An autoprefixer can save you time and effort by automatically adding the necessary prefixes to your stylesheets.These are just a few of the many useful CSS tools that are available. By using these tools, you can streamline your workflow and create beautiful, functional websites and applications more efficiently.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
    {
      id: 2,
      title: 'Bratislava Places That Highlight The City',
      category: 'travel',
      subHeader: 'Discover the Best of Bratislava with These Must-See Attractions',
      subCategory: ['vacation', 'holidays', 'sight seeing'],
      description:
        "Bratislava is the capital city of Slovakia, and it is a vibrant and diverse destination that offers something for everyone. From stunning historical landmarks to modern cultural attractions, Bratislava has a lot to offer. Here are some of the places that highlight the city.Bratislava Castle: This stunning castle is a must-see for anyone visiting Bratislava. Built in the 9th century, the castle has a rich history and has undergone numerous renovations and renovations over the years. Today, it houses a number of museums and galleries, including the Slovak National Museum and the Museum of History.St. Martin's Cathedral: This impressive cathedral is a symbol of Bratislava and one of the city's most iconic landmarks. Located in the heart of the city, St. Martin's Cathedral is a Romanesque-Gothic structure that dates back to the 14th century. It is a popular tourist attraction and a popular location for weddings and other ceremonies.Old Town: Bratislava's Old Town is a charming and picturesque part of the city that is filled with narrow streets, cobblestone squares, and beautiful architecture. It is a great place to wander and explore, and there are numerous cafes, restaurants, and shops to visit. The Old Town is also home to a number of important historical landmarks, including the Bratislava City Museum and the Primate's Palace.Slovak National Theatre: The Slovak National Theatre is a cultural gem in Bratislava and an important venue for music, dance, and theater performances. The theater is home to several artistic companies, including the Slovak National Ballet and the Slovak National Opera.Danube River: The Danube River is an iconic waterway that runs through Bratislava and offers a number of recreational activities. You can take a boat tour of the river, go fishing, or simply relax along the riverbank and enjoy the views.Bratislava Zoo: Located on the outskirts of the city, the Bratislava Zoo is home to a wide variety of animals, including lions, tigers, elephants, and gorillas. It is a great place to spend the day with the family, and there are a number of interactive exhibits and educational programs offered.Museum of Transport: If you are interested in transportation and technology, the Museum of Transport is a must-see in Bratislava. Located in the city's historic depot, the museum features a collection of vintage cars, trains, and other vehicles, as well as interactive exhibits and hands-on displays.These are just a few of the many places that highlight the city of Bratislava. Whether you are interested in history, culture, or just enjoying the outdoors, there is something for everyone in this vibrant and dynamic city.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
    {
      id: 3,
      title: 'Online Shopping – An Alternative to Shopping in the Mall',
      category: 'travel',
      subHeader: 'Maximize Your Productivity with These Must-Have CSS Utilities',
      subCategory: ['e-commerce store', 'clothing', 'shopping store'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
    {
      id: 4,
      title: 'Youth Exchange in Romania',
      category: 'travel',
      subHeader: 'A Life-Changing Experience: My 10 Days in Romania on an Ecology Project',
      subCategory: ['Youth Exchange', 'Youth Exchange', 'Erasmus+'],
      description:
        "It was a cold and drizzly morning when I boarded the plane to Romania for a 10-day youth exchange on a project about ecology. As I settled into my seat, I couldn't help but feel a mix of excitement and nerves. I had never been to Romania before, and I didn't know anyone on the trip. But as the plane lifted off the ground, I felt a sense of adventure wash over me.When we arrived in Romania, we were met by a group of friendly volunteers who would be hosting us during our stay. They took us to a cozy guesthouse in the countryside, where we would be staying for the next week.Over the next few days, we participated in a variety of activities and workshops focused on environmental sustainability and conservation. We learned about the importance of protecting natural resources, reducing waste, and preserving biodiversity. We also had the opportunity to visit a local school and teach the about how important is ecology for the enviroment.In addition to the educational activities, we also had the chance to explore the local culture and make new friends. We visited historical landmarks and museums, sampled local cuisine, and participated in traditional folk dancing and music.As the trip came to a close, I felt a sense of accomplishment and gratitude. I had learned so much about the environment and sustainability, and I had made some lasting friendships. As I boarded the plane back home, I couldn't wait to share my experiences with others and continue working to protect the planet.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
    {
      id: 5,
      title: 'Top tech companies',
      category: 'tech',
      subHeader: 'Maximize Your Productivity with These Must-Have CSS Utilities',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
    {
      id: 6,
      title: 'Beyond the Beach',
      category: 'travel',
      subHeader: 'Maximize Your Productivity with These Must-Have CSS Utilities',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover:
        'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
    {
      id: 7,
      title: 'Art & Perspective',
      category: 'design',
      subHeader: 'Maximize Your Productivity with These Must-Have CSS Utilities',
      subCategory: ['skill', 'design', 'passion'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Ampas Theodoros',
      authorAvatar: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Face',
      createdAt: 'January 03, 2022',
      cover: 'https://via.placeholder.com/1000/B68E71/282A3A/?text=Post',
    },
  ];